### ISSUE TITLE
Incrementing version

### ISSUE THREAD

**Issue by johndharrison** [zmarko/semver#1]
Hi Marko 

Thanks for your work on semver cpp, Did you have any plans to increment/decrement a version by a specified level (major, minor patch  etc..). Something akin to the -i --increment option in https://github.com/npm/node-semver

**Comment by zmarko** [comment]
Hi, thanks for your interest in this project. I haven't had a need for such a functionality, but, it is something I would consider adding in. I took a look at the node semver parser you linked. It contains some stuff that's node-specific and differs from pure semver specification. If we stick to pure semver, for now, this is how I see possible implementation:

- Only major, minor and patch version components can be incremented or decremented.
- Incrementing one version component would automatically reset lower level version components to zero (e.g. incrementing major component of version 1.2.3 would yield 2.0.0).
- Incrementing any one of normal version components (major, minor, patch) would remove any pre-release or build version components.
- Increment can be positive or negative integer, as long as de/incremented version component remains within legalrange (equal or greater than 0, lower than 65536). 

Does this sound like something useful?

**Comment by johndharrison** [comment]
That sounds perfect!! It may be useful to have a setter function in the Semver200_version so that a user 
can manually set version values so for example `v.prerelease("alpha")` would set the `prerelease` string to alpha. Just a thought but definitely what you outlined above will be great.

**Comment by zmarko** [comment]
Initial implementation is in a new branch (https://github.com/zmarko/semver/tree/version_inc). Version objects now support a couple of new methods:
- set_major(minor, patch, prerelease, build) which creates a new Version object copy and sets appropriate field to specified value.
- reset_major(minor, patch, prerelease, build) which creates a new Version object copy, sets appropriate field to specified value and resets all the other fields to default (zero) values.
- inc_major(minor, patch) which creates a new Version object copy, increases or decreases (with negative increment) appropriate field and resets other fields to default (zero) values.

Could you try it out and see if it's what you had in mind?

Note that I kept all Version objects immutable and all setters return new objects.

**Comment by johndharrison** [comment]
On some platforms I am getting the following errors:

https://travis-ci.org/johndharrison/semver/jobs/188696248#L940

I added 
```
#include <stdexcept>
```
to version.h and that seemed to fix it. (I am compiling with C++11 however with:

defined in version.h
```
struct unamed_lambda
	{
	  template<typename T>
	  std::string operator()(T& id) const {return id.first;}
	};

struct unamed_lambda2
	{
	  template<typename T>
	  std::string operator()(T& id) const {return id;}
};
```
changed in version.inl

```
	template<typename Parser, typename Comparator, typename Modifier>
	const std::string Basic_version<Parser, Comparator, Modifier>::prerelease() const {
		std::stringstream ss;
		splice(ss, ver_.prerelease_ids, ".", unamed_lambda());
		return ss.str();
	}

	template<typename Parser, typename Comparator, typename Modifier>
	const std::string Basic_version<Parser, Comparator, Modifier>::build() const {
		std::stringstream ss;
		splice(ss, ver_.build_ids, ".", unamed_lambda2());
		return ss.str();
	}
```

so that may have caused issues. I think I have got things working and will play around with the new functionality and report back !!

**Comment by johndharrison** [comment]
Marko, 

I have checked through the added methods. They work perfectly. Thank you for adding this functionality.

**Comment by zmarko** [comment]
No problem, thank you for suggesting new feature. I'll update the docs and release a new version as soon as I find some time.

**Comment by zmarko** [comment]
I'll close this issue now as the new code is merged into master.

**Comment by johndharrison** [comment]
Thanks once again Marko. I have used semver cpp in an R package https://cran.r-project.org/package=semver

**Comment by zmarko** [comment]
It's great seeing this used in the wild. Thanks for attribution :).

**Comment by beevabeeva** [comment]
> Thanks once again Marko. I have used semver cpp in an R package https://cran.r-project.org/package=semver

@johndharrison Sorry to sound rude, but what is the point if you cannot even use semver for the `version` field in the `DESCRIPTION` file of an R package?
I wish R would change this and get with the standards already.


![image](https://user-images.githubusercontent.com/19332617/103857878-fd163a00-50bf-11eb-8041-6592c7e14ad6.png)

**Comment by zmarko** [comment]
@beevabeeva I am not the author of the R extension and not really familiar with R ecosystem, but, based on the message you've pasted and the https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file:

> The mandatory ‘Version’ field gives the version of the package. This is a sequence of at least two (and usually three) non-negative integers separated by single ‘.’ or ‘-’ characters. The canonical form is as shown in the example, and a version such as ‘0.01’ or ‘0.01.0’ will be handled as if it were ‘0.1-0’. It is not a decimal number, so for example 0.9 < 0.75 since 9 < 75. 

it appears that you can use only integers in version.

**Comment by beevabeeva** [comment]
> @beevabeeva I am not the author of the R extension and not really familiar with R ecosystem, but, based on the message you've pasted and the https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file:
> 
> > The mandatory ‘Version’ field gives the version of the package. This is a sequence of at least two (and usually three) non-negative integers separated by single ‘.’ or ‘-’ characters. The canonical form is as shown in the example, and a version such as ‘0.01’ or ‘0.01.0’ will be handled as if it were ‘0.1-0’. It is not a decimal number, so for example 0.9 < 0.75 since 9 < 75.
> 
> it appears that you can use only integers in version.

Yes I know that. That is the problem! I know you or @johndharrison don't have control over that. Just venting my frustration :stuck_out_tongue:
